config/routes.rb
Rails.application.routes.draw do

  resources :product_validators
  resources :codes do
    collection { post :import }
  end

  resources :softwares do
    resources :software_assigns
  end

  resources :products do
    resources :registrations
  end

  resources :software_downloads

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end
    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/software.rb
# == Schema Information
#
# Table name: softwares
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Software < ActiveRecord::Base
  has_many :software_assigns
  has_many :products, through: :software_assigns
  has_many :software_downloads
  has_many :codes
end

app/controllers/softwares_controller.rb
# == Schema Information
#
# Table name: softwares
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class SoftwaresController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_admin
  before_action :set_software, only: [:show, :edit, :update, :destroy]

  def index
    @softwares = Software.all
  end

  def show
  end

  def new
    @software = Software.new
  end

  def edit
  end

  def create
    @software = Software.new(software_params)
    if @software.save
      redirect_to softwares_path, :notice => 'Software title was successfully created.'
    else
      render :new, :alert => 'Unable to create software title! Please try again.'
    end
  end

  def update
    if @software.update(software_params)
      redirect_to softwares_path, :notice => 'Software title was successfully updated.'
    else
      render :edit, :alert => 'Unable to update software title! Please try again.'
    end
  end

  def destroy
    @software.destroy
    redirect_to softwares_path, :alert => 'Software title was successfully destroyed.'
  end


  private
    def set_software
      @software = Software.find(params[:id])
    end

    def software_params
      params.require(:software).permit(:title)
    end
end

app/helpers/softwares_helper.rb
# == Schema Information
#
# Table name: softwares
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module SoftwaresHelper
end

app/views/softwares/_form.html.erb
<%= simple_form_for(@software) do |f| %>
  <%= f.error_notification %>



  <br>
  <div class="form-inputs">
    <%= f.input :title %>
  </div>

  <br>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-warning' %>
  </div>

  <br>
<% end %>

app/views/softwares/edit.html.erb
<div class="container">
  <div class="well">
    <h1>Editing Software</h1>

    <%= render 'form' %>

    <br>
    <hr>
    <%= link_to 'Back', softwares_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/softwares/index.html.erb
<div class="container">
  <div class="well">

    <h1>Software Titles:</h1>
    <br>
    <%= link_to 'Create Software Title', new_software_path, class: 'btn btn-warning' %>
    <br><br>

    <table class="table">
      <thead>
        <tr>
          <th>Software ID</th>
          <th>Software Title</th>
        </tr>
      </thead>

      <tbody>
        <% @softwares.each do |software| %>
          <tr>
            <td><%= software.id %></td>
            <td><%= software.title %></td>

            <% if current_user.admin? %>
              <td><%= link_to 'Edit', edit_software_path(software), class: 'btn btn-primary' %></td>
              <td><%= link_to 'Destroy', software, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <td><%= link_to 'Assign to Product', new_software_software_assign_path(software), class: 'btn btn-success' %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div> <!-- well -->
</div> <!-- container -->

app/views/softwares/new.html.erb
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">


        <h1>New Software Title</h1>

        <%= render 'form' %>

        <br>
        <hr>
        <%= link_to 'Back', softwares_path, class: 'btn btn-primary' %>
      </div> <!-- col -->
    </div> <!-- row -->
  </div> <!-- well -->
</div> <!-- container -->