config/routes.rb
Rails.application.routes.draw do

  resources :product_validators
  resources :codes do
    collection { post :import }
  end

  resources :softwares do
    resources :software_assigns
  end

  resources :products do
    resources :registrations
  end

  resources :software_downloads

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end
    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id               :integer          not null, primary key
#  product_name     :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  product_image_id :string
#

class Product < ActiveRecord::Base
  attachment :product_image
  has_many :registrations
  has_many :users, through: :registrations
  has_many :software_assigns
  has_many :softwares, through: :software_assigns
  has_many :product_validators
end

app/controllers/products_controller.rb
# == Schema Information
#
# Table name: products
#
#  id               :integer          not null, primary key
#  product_name     :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  product_image_id :string
#

class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_admin, except: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, :notice => 'Product was successfully created.'
    else
      render :new, :alert => 'Unable to create product! Please try again.'
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, :notice => 'Product was successfully updated.'
    else
      render :edit, :alert => 'Unable to update product! Please try again.'
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, :alert => 'Product was successfully destroyed.'
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:product_name, :product_image, :remove_product_image)
    end
end

app/helpers/products_helper.rb
# == Schema Information
#
# Table name: products
#
#  id               :integer          not null, primary key
#  product_name     :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  product_image_id :string
#

module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>

  <br>
  <div class="form-group">
    <%= f.label :upload_product_image %>
    <%= f.attachment_field :product_image %>
  </div>

  <br>
  <div class="form-group">
    <%= f.check_box :remove_product_image %>
    <%= f.label     :remove_product_image %>
  </div>

  <br>
  <div class="form-inputs">
    <%= f.input :product_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-warning' %>
  </div>

  <br>
<% end %>

app/views/products/edit.html.erb
<div class="container">
  <div class="well">
    <h1>Editing Product</h1>

    <div class="product_edit_image_container">
      <%= image_tag attachment_url(@product, :product_image, :fill, 100, 100, format: "png") %>
    </div>

    <%= render 'form' %>

    <br>
    <hr>
    <%= link_to 'Show', @product, class: 'btn btn-primary' %>
    <%= link_to 'Back', products_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="well">

    <h1>Listing Products</h1>
    <br>
    <% if current_user.admin? %>
      <%= link_to 'New Product', new_product_path, class: 'btn btn-warning' %>
    <% end %>
    <br><br>

    <table class="table">
      <thead>
        <tr>
          <th>Image:</th>
          <th>Product Name:</th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= image_tag attachment_url(product, :product_image, :fill, 100, 100, format: "png") %></td>
            <td><%= product.product_name %></td>
            <td><%= link_to 'Register', new_product_registration_path(product), class: 'btn btn-warning' %></td>

            <% if current_user.admin? %>
              <td><%= link_to 'Show', product, class: 'btn btn-success' %></td>
              <td><%= link_to 'Edit', edit_product_path(product), class: 'btn btn-primary' %></td>
              <td><%= link_to 'Destroy', product, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div> <!-- well -->
</div> <!-- container -->

app/views/products/new.html.erb
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">


        <h1>New Product</h1>

        <%= render 'form' %>

        <br>
        <hr>
        <%= link_to 'Back', products_path, class: 'btn btn-primary' %>
      </div> <!-- col -->
    </div> <!-- row -->
  </div> <!-- well -->
</div> <!-- container -->

app/views/products/show.html.erb
<div class="container">
  <div class="well">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Product name:</strong>
      <%= @product.product_name %>
    </p>
    <div class="product_show_image_container">
      <%= image_tag attachment_url(@product, :product_image, :fill, 100, 100, format: "png") %>
    </div>

    <br><br>

    <h4>Associated Software:</h4>
    <hr>
    <ol>
      <% @product.softwares.each do |software| %>
        <li><%= software[:title] %></li>
      <% end %>
    </ol>


    <br>
    <hr>
    <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-primary' %> |
    <%= link_to 'Back', products_path, class: 'btn btn-success' %>
    <%= link_to 'Register', new_product_registration_path(@product), class: 'btn btn-warning' %>
  </div> <!-- well -->
</div> <!-- container -->