config/routes.rb
Rails.application.routes.draw do

  resources :product_validators
  resources :codes do
    collection { post :import }
  end

  resources :softwares do
    resources :software_assigns
  end

  resources :products do
    resources :registrations
  end

  resources :software_downloads

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end
    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/software_download.rb
# == Schema Information
#
# Table name: software_downloads
#
#  id          :integer          not null, primary key
#  software_id :integer
#  title       :string
#  url         :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class SoftwareDownload < ActiveRecord::Base
  belongs_to :software
  accepts_nested_attributes_for :software
end

app/controllers/software_downloads_controller.rb
# == Schema Information
#
# Table name: software_downloads
#
#  id          :integer          not null, primary key
#  software_id :integer
#  title       :string
#  url         :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class SoftwareDownloadsController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_admin
  before_action :set_software, only: [:new, :edit, :update, :destroy]
  before_action :set_software_downloads, only: [:show, :edit, :update, :destroy]

  def index
    @software_downloads = SoftwareDownload.all
  end

  def show
  end

  def new
    @software_download = SoftwareDownload.new
  end

  def edit
  end

  def create
    @software_download = SoftwareDownload.new(software_downloads_params)
    if @software_download.save
      redirect_to software_downloads_path, :notice => 'Software link was successfully created.'
    else
      render :new, :alert => 'Unable to create software link! Please try again.'
    end
  end

  def update
    if @software_download.update(software_downloads_params)
      redirect_to software_downloads_path, :notice => 'Software link was successfully updated.'
    else
      render :edit, :alert => 'Unable to update software link! Please try again.'
    end
  end

  def destroy
    @software_download.destroy
    redirect_to software_downloads_path, :alert => 'Software link was successfully destroyed.'
  end


  private
    def set_software_downloads
      @software_download = SoftwareDownload.find(params[:id])
    end

    def set_software
      @software = Software.all
    end

    def software_downloads_params
      params.require(:software_download).permit(:software_id, :title, :url)
    end
end

app/helpers/software_downloads_helper.rb
# == Schema Information
#
# Table name: software_downloads
#
#  id          :integer          not null, primary key
#  software_id :integer
#  title       :string
#  url         :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

module SoftwareDownloadsHelper
end

app/views/software_downloads/_form.html.erb
<%= simple_form_for(@software_download) do |f| %>

  <br>

    <%# f.collection_select(:software_id, @software, :id, :title) %>
    <%= f.association :software %>

  <br>
  <div class="form-inputs">
    <%= f.input :title %>
  </div>

  <br>
  <div class="form-inputs">
    <%= f.input :url %>
  </div>

  <br>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-warning' %>
  </div>

  <br>
<% end %>

app/views/software_downloads/edit.html.erb
<div class="container">
  <div class="well">
    <h1>Editing Download Link</h1>

    <%= render 'form' %>

    <br>
    <hr>
    <%= link_to 'Back', software_downloads_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/software_downloads/index.html.erb
<div class="container">
  <div class="well">

    <h1>Software Downloads Links:</h1>
    <br>
    <%= link_to 'Add Software Link', new_software_download_path, class: 'btn btn-warning' %>
    <br><br>

    <table class="table">
      <thead>
        <tr>
          <th>Software Title</th>
          <th>Software Url</th>
        </tr>
      </thead>

      <tbody>
        <% @software_downloads.each do |software| %>
          <tr>
            <td><%= software.title %></td>
            <td><%= software.url %></td>

            <% if current_user.admin? %>
              <td><%= link_to 'Edit', edit_software_download_path(software), class: 'btn btn-primary' %></td>
              <td><%= link_to 'Destroy', software_download_path(software), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div> <!-- well -->
</div> <!-- container -->

app/views/software_downloads/new.html.erb
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">


        <h1>New Software Link</h1>

        <%= render 'form' %>

        <br>
        <hr>
        <%= link_to 'Back', software_downloads_path, class: 'btn btn-primary' %>
      </div> <!-- col -->
    </div> <!-- row -->
  </div> <!-- well -->
</div> <!-- container -->