config/routes.rb
Rails.application.routes.draw do

  resources :product_validators
  resources :codes do
    collection { post :import }
  end

  resources :softwares do
    resources :software_assigns
  end

  resources :products do
    resources :registrations
  end

  resources :software_downloads

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end
    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
  <li><%= link_to 'My Profile', user_path(current_user) %></li>
  <li><%= link_to 'Products', products_path %></li>

<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'Software', softwares_path %></li>
    <li><%= link_to 'Software(CDN)', software_downloads_path %></li>
    <li><%= link_to 'Upload Codes', new_code_path %></li>
    <li><%= link_to 'Validators', product_validators_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "In Music Rails" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "In Music Rails" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>